#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : deprecated-chardet
Version  : 3.0.4
Release  : 38
URL      : http://pypi.debian.net/chardet/chardet-3.0.4.tar.gz
Source0  : http://pypi.debian.net/chardet/chardet-3.0.4.tar.gz
Summary  : Universal encoding detector for Python 2 and 3
Group    : Development/Tools
License  : LGPL-2.1
Requires: deprecated-chardet-bin = %{version}-%{release}
Requires: deprecated-chardet-license = %{version}-%{release}
Requires: deprecated-chardet-python = %{version}-%{release}
BuildRequires : buildreq-distutils
BuildRequires : buildreq-distutils3

%description
Chardet: The Universal Character Encoding Detector
--------------------------------------------------

%package bin
Summary: bin components for the deprecated-chardet package.
Group: Binaries
Requires: deprecated-chardet-license = %{version}-%{release}

%description bin
bin components for the deprecated-chardet package.


%package legacypython
Summary: legacypython components for the deprecated-chardet package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the deprecated-chardet package.


%package license
Summary: license components for the deprecated-chardet package.
Group: Default

%description license
license components for the deprecated-chardet package.


%package python
Summary: python components for the deprecated-chardet package.
Group: Default

%description python
python components for the deprecated-chardet package.


%prep
%setup -q -n chardet-3.0.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1554308898
export MAKEFLAGS=%{?_smp_mflags}
python2 setup.py build -b py2

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/deprecated-chardet
cp LICENSE %{buildroot}/usr/share/package-licenses/deprecated-chardet/LICENSE
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/chardetect

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/deprecated-chardet/LICENSE

%files python
%defattr(-,root,root,-)
